### PR TITLE
Fix pickup issues

### LINKED ISSUE #591: Various pickup problems
Some pickup/item issues in V1.8.1:

- Similar to enemy drops, one-item limit should set the `unobtainable_pickup` count in the gameflow to avoid confusion when checking the statistics.
- When skidoo drivers are converted to pickups (to reduce savegame usage) sometimes the items are unreachable despite being floored.
- If randomizing secret rewards, but not secrets in TR1, extra reward items are placed in non-existent reward rooms.
- A particular secret in Bartoli's Hideout can become unreachable after blowing up the final area.
- If Dragon's Lair has an additional door before the arena, pickup items on the neighbouring tiles (which become walls) are no longer reachable.

### PR DESCRIPTION
**Pull request by lahm86**
Resolves #591.

#### Checklist

- [x] I have read the [coding conventions](https://github.com/LostArtefacts/TR-Rando/blob/master/CONTRIBUTING.md#coding-conventions)
- [x] I have read the [testing guidelines](https://github.com/LostArtefacts/TR-Rando/blob/master/CONTRIBUTING.md#testing-guidelines)
- [x] I have added a changelog entry about what my pull request accomplishes, or it is an internal change

#### Description

The logic for converting skidoo drivers is a workaround to avoid crashes in TR2 when too many of those are present (the savegame buffer cannot cope). Before we were converting extra drivers into pickups and then just flooring the items, but lots of these would still end up in unreachable places. Now we just shift them to another existing pickup in the level.

The changes for the other fixes are quite straight-forward.

### CODE REVIEW

File: TRRandomizerCore/Randomizers/TR1/TR1SecretRewardRandomizer.cs [hunk 1]
```diff
@@ -49,9 +49,12 @@ private void RandomizeRewards(TR1CombinedLevel level)
         stdItemTypes.Remove(TR1Type.Pistols_S_P); // A bit cruel as a reward?
 
         int secretRoom = RoomWaterUtilities.DefaultRoomCountDictionary[level.Name];
```
Comment (chreden) [inline TRRandomizerCore/Randomizers/TR1/TR1SecretRewardRandomizer.cs:51]: `secretRoom` looks to be unused now

Comment (lahm86) [reply TRRandomizerCore/Randomizers/TR1/TR1SecretRewardRandomizer.cs]: Oh yes, I wonder why VS didn't notice that.

**Review by chreden — APPROVED** [review]
