### PR TITLE
TR3 Fix Monkey Vehicle Crash

### LINKED ISSUE #466: TR3 - Friendly monkeys and vehicles cause crashes
If Lara mounts a vehicle while a friendly monkey is active, the game crashes.

### PR DESCRIPTION
**Pull request by lahm86**
Various monkey-tiger-vehicle crash workarounds.

Cross-level enemy rando:
- If monkeys are picked first in the enemy pool and a vehicle is present, tigers will never be picked
- If tigers are picked first in the enemy pool and a vehicle is present, monkeys will never be picked

Native enemy rando:
- If a vehicle and the monkey and tiger models are present, either the monkey or tiger model will be banished (only Jungle affected essentially)

No enemy rando:
- If a UPV has been added to cold water levels (if sequencing or weather is being randomized), an additional check will ensure tigers are removed where monkeys exist (so again, only Jungle affected)

Resolves #466.

### CODE REVIEW

File: TRLevelReader/Helpers/TR3EntityUtilities.cs [hunk 1]
```diff
@@ -359,6 +359,14 @@ public static bool IsAnyPickupType(TR3Entities entity)
                 || IsArtefactPickup(entity);
         }
 
+        public static bool IsVehicleType(TR3Entities entityType)
+        {
+            return entityType == TR3Entities.Quad
+                || entityType == TR3Entities.Kayak
+                || entityType == TR3Entities.UPV
+                || entityType == TR3Entities.MineCart;
```
Comment (chreden) [inline TRLevelReader/Helpers/TR3EntityUtilities.cs:367]: What about the Antarctica boat?

File: TRRandomizerCore/Levels/TR3CombinedLevel.cs [hunk 2]
```diff
@@ -114,5 +119,16 @@ public TR3Adventure Adventure
...
         }
+
+        public void RemoveModel(TR3Entities type)
+        {
+            List<TRModel> models = Data.Models.ToList();
+            if (models.Find(m => m.ID == (uint)type) is TRModel model)
+            {
+                models.Remove(model);
+                Data.Models = models.ToArray();
+                Data.NumModels--;
```
Comment (chreden) [inline TRRandomizerCore/Levels/TR3CombinedLevel.cs:130]: Outside of the scope of this PR but `NumModels` looks like a bug waiting to happen if you ever forget to update it - it should just be able to take the length of the array. It could be 

You can keep the property for getting:
```
public int NumModels => Models.Length;
```

**Review by chreden — CHANGES_REQUESTED** [review]

File: TRLevelReader/Helpers/TR3EntityUtilities.cs (hunk 1 above)
Comment (lahm86) [reply TRLevelReader/Helpers/TR3EntityUtilities.cs:368]: Completely forgot about the boat. Now added.

File: TRRandomizerCore/Levels/TR3CombinedLevel.cs (hunk 2 above)
Comment (lahm86) [reply TRRandomizerCore/Levels/TR3CombinedLevel.cs:130]: Agreed. I'd like to change all the arrays in the level classes to lists to avoid this kind of thing, which we have in a *lot* of places.
```
List<T> list = level.ThingArray.ToList();
list.Add(new T());
level.ThingArray = list.ToArray();
level.NumThings++;
```
The goal being `level.ThingList.Add(new T());` and nothing else.

It'll be a sizeable change, but less code in the end. I'll raise an issue to tackle this separately.

**Review by chreden — APPROVED** [review]
